kind: pipeline
name: default

steps:
- name: test
  image: alpine/git
  commands:
  - echo "Sleeping 30 s"
  - sleep 30
  # fail the build if the last commit message contains `ci:fail`
  - git log -1 --oneline | grep -v 'ci:fail'
  when:
    branches:
    - dev
    - master
    - release-*
    - testing*
    - trying
    - staging

