status = [
  "continuous-integration/drone/push"
]

# Ensure that reviewers (all of us!) can't merge their own PRs without review.
# This is possible, because Github doesn't allow self-review.
# required_approvals = 1

# Number of seconds from when a merge commit is created to when its statuses must pass.
timeout_sec = 7200

delete_merged_branches = true
